version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD : ${DB_PASSWORD}
      MYSQL_DATABASE : ${DATABASE}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/volume/:/docker-entrypoint-initdb.d/
    networks:
      - dailyMaple

  backend:
    build:
      context: ../daily-maple/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - dailyMaple
    links:
      - db

networks:
  dailyMaple:
    driver: bridge