spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
