spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.209.150.31:3306/dm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rootroot

springdoc:
    swagger-ui:
      path: api
      tags-sorter: alpha
      operations-sorter: alpha
    paths-to-match:
      - /**


server:
  port: 8080