spring:
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          kakao:
            client_id: ${CLIENT_ID}

springdoc:
    swagger-ui:
      path: api
      tags-sorter: alpha
      operations-sorter: alpha
    paths-to-match:
      - /**

server:
  port: 8080