spring:
  profiles:
    active: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
springdoc:
    swagger-ui:
      path: api
      tags-sorter: alpha
      operations-sorter: alpha
    paths-to-match:
      - /**


server:
  port: 8080